insert into categories(id, name) values (1, 'Category 1')
insert into categories(id, name) values (2, 'Category 2')
insert into categories(id, name) values (3, 'Category 3')
insert into categories(id, name) values (4, 'Category 4')
insert into categories(id, name) values (5, 'Category 5')

insert into pages(id, title, category_id, author) values (1, 'Page One', 1, 'Author One')
insert into pages(id, title, category_id, author) values (2, 'Page Two', 2, 'Author Two')
insert into pages(id, title, category_id, author) values (3, 'Page Three', 3, 'Author Three')
insert into pages(id, title, category_id, author) values (4, 'Page Four', 4, 'Author Four')
insert into pages(id, title, category_id, author) values (5, 'Page Five', 5, 'Author Five')